#!/bin/bash
echo "node"
sudo apt update
sudo apt install nodejs npm

echo "update node"
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

echo "yarn"
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
yarn global add @vue/cli
